// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIlvCF01QiSZxiQAoJHqZSIjZCuR27ds',
    appId: '1:421103918614:web:6f51908947e95c67281f37',
    messagingSenderId: '421103918614',
    projectId: 'vitrine-adm-14879',
    authDomain: 'vitrine-adm-14879.firebaseapp.com',
    storageBucket: 'vitrine-adm-14879.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nb_qTEU-XAQq4aKAHq-3FTqQOOa2JBM',
    appId: '1:421103918614:android:debc9ea16f9abc96281f37',
    messagingSenderId: '421103918614',
    projectId: 'vitrine-adm-14879',
    storageBucket: 'vitrine-adm-14879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQqxFyNoiY9TPoRXRJkQzObYGKarS_0Yo',
    appId: '1:421103918614:ios:f0f8597a8f74acc2281f37',
    messagingSenderId: '421103918614',
    projectId: 'vitrine-adm-14879',
    storageBucket: 'vitrine-adm-14879.appspot.com',
    iosClientId: '421103918614-srv108gvmr1bldi63erip1aon3i1bqre.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitrine',
  );
}
